[package]
name = "shades"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
rfd = "0.14.1"
image = "0.25.2"
rpassword = "7.3.1"
rand_core = "0.6.4"
aes-gcm = "0.10.3"
argon2 = "0.5.3"
password-hash = "0.5"
hex = "0.4.3"
